### ISSUE TITLE
Google analytics not configured correctly

### ISSUE THREAD

**Issue by jensg** [ordina-ncore/ordina-ncore.github.io#17]
Do we need google analytics?
If so: we should register an account.

**Comment by Turbots** [comment]
Hey guys, I would indeed appreciate that you either:
- remove the google analytics script until you know what you wanna do with it
- create a google account and change the content of the tracker ID in the script, since you're pointing to the JWorks tracker ID right now, which could mess up our analytics

Good luck with the blog 👍

**Comment by timhulstaert** [comment]
removed the google analytics script for the time being

**Comment by timhulstaert** [comment]
mail address approved and google analytics account has been set up
